#
# Common parts for the firmware generation
#

noinst_PROGRAMS += fw_writer

fw_writer = fw_writer$(EXEEXT)

LINK_FOR_BUILD = $(CC_FOR_BUILD) $(CFLAGS_FOR_BUILD) $(CPPFLAGS_FOR_BUILD) $(LDFLAGS_FOR_BUILD) $(TARGET_ARCH_FOR_BUILD)

$(fw_writer_OBJECTS) : CC=$(CC_FOR_BUILD)
$(fw_writer_OBJECTS) : CFLAGS=$(CFLAGS_FOR_BUILD)
$(fw_writer_OBJECTS) : CPPFLAGS=$(CPPFLAGS_FOR_BUILD)

fw_writer$(EXEEXT): $(fw_writer_OBJECTS)
	$(LINK_FOR_BUILD) $^ $(LDLIBS_FOR_BUILD) -o $@
